automation: !include_dir_merge_list automation/
input_number: !include_dir_merge_named input_number/
switch:
  - platform: template
    switches: !include_dir_merge_named switch/
timer: !include_dir_merge_named timer/
