- id: '1740479595607'
  alias: 'Licht: Bibliothek Steckdose deaktiviert'
  description: ''
  triggers:
  - entity_id: switch.steckdose_bibliothek
    to: 'off'
    trigger: state
  conditions: []
  actions:
  - target:
      entity_id: light.bibliothek
    data:
      transition: 5
    action: light.turn_off
  mode: single
- id: '1740479735250'
  alias: 'Licht: Bibliothek Steckdose aktiviert'
  description: ''
  triggers:
  - entity_id: switch.steckdose_bibliothek
    to: 'on'
    trigger: state
  conditions: []
  actions:
  - sequence:
    - action: light.turn_on
      target:
        entity_id: light.bibliothek
      data:
        transition: 5
        brightness: 10
  mode: single
