- id: '1767814546683'
  alias: 'Bibliothek Hub: Wenn Taste Arbeit gedrückt dann Szene Arbeit'
  description: ''
  triggers:
  - trigger: event
    event_type: ''
  - trigger: state
    entity_id:
    - event.hub_bibliothek_button_arbeit_taste
    attribute: event_type
    to:
    - initial_press
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.arbeit
    data: {}
  mode: single
- id: '1772034110361'
  alias: 'Update Sensors: addon_running_states'
  description: ''
  triggers:
  - trigger: time_pattern
    seconds: /10
  conditions: []
  actions:
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
      - binary_sensor.sqlite_web_lauft
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
      - binary_sensor.studio_code_server_lauft
  mode: single
