- id: '1767814546683'
  alias: 'Bibliothek Hub: Wenn Taste Arbeit gedrückt dann Szene Arbeit'
  description: ''
  triggers:
  - trigger: event
    event_type: ''
  - trigger: state
    entity_id:
    - event.hub_bibliothek_button_arbeit_taste
    attribute: event_type
    to:
    - initial_press
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.arbeit
    data: {}
  mode: single
- id: '1772034110361'
  alias: 'Update Sensors: addon_running_states'
  description: ''
  triggers:
  - trigger: time_pattern
    seconds: /10
  conditions: []
  actions:
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
      - binary_sensor.sqlite_web_lauft
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
      - binary_sensor.studio_code_server_lauft
  mode: single
- id: '1772037656469'
  alias: 'Update Sensor: door_window_remaining_time'
  description: ''
  triggers:
  - trigger: time_pattern
    seconds: /1
  conditions:
  - condition: state
    entity_id: timer.door_window_reset_alarm
    state:
    - active
  actions:
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
      - sensor.door_window_remaining_time
  mode: single
- id: '1772037903349'
  alias: 'Tür & Fenster Alarm: Countdown zum reaktivieren starten'
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.door_window_alarm_disabled
    to:
    - 'on'
  conditions: []
  actions:
  - action: timer.start
    metadata: {}
    target:
      entity_id: timer.door_window_reset_alarm
    data: {}
  mode: single
- id: '1772038407252'
  alias: 'Tür & Fenster Alarm: Reaktivieren'
  description: ''
  triggers:
  - trigger: event
    event_type: timer.finished
    event_data:
      entity_id: timer.door_window_reset_alarm
  - trigger: event
    event_type: timer.cancelled
    event_data:
      entity_id: timer.door_window_reset_alarm
  conditions: []
  actions:
  - action: input_boolean.turn_off
    metadata: {}
    target:
      entity_id: input_boolean.door_window_alarm_disabled
    data: {}
  mode: single
- id: '1772038806959'
  alias: 'Tür & Fenster Alarm: Countdown zum reaktivieren abbrechen'
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.door_window_alarm_disabled
    to:
    - 'off'
  - trigger: state
    entity_id:
    - zone.home
    to:
    - '0'
  conditions: []
  actions:
  - action: timer.cancel
    metadata: {}
    target:
      entity_id: timer.door_window_reset_alarm
    data: {}
  mode: single
- id: '1772040225277'
  alias: 'Alle Türen/Fenster geschlossen: Meldung löschen'
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.alle_fenster
    to:
    - 'off'
  - trigger: state
    entity_id:
    - binary_sensor.alle_turen
    to:
    - 'off'
  conditions:
  - condition: state
    entity_id: binary_sensor.alle_fenster
    state:
    - 'off'
  - condition: state
    entity_id: binary_sensor.alle_turen
    state:
    - 'off'
  actions:
  - action: notify.all_mobile_apps
    metadata: {}
    data:
      message: clear_notification
      data:
        tag: ha_doorwindow
  mode: parallel
  max: 10
- id: '1772040970604'
  alias: 'Offene Tür/Fenster erkannt: Melden'
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.turen
    to:
    - 'on'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  - trigger: state
    entity_id:
    - binary_sensor.fenster
    to:
    - 'on'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  - trigger: state
    entity_id:
    - zone.home
    to:
    - O
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.door_window_alarm_disabled
      state:
      - 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.alle_turen
        state:
        - 'on'
      - condition: state
        entity_id: binary_sensor.alle_fenster
        state:
        - 'on'
  actions:
  - sequence:
    - action: notify.all_mobile_apps
      metadata: {}
      data:
        message: clear_notification
        data:
          tag: ha_doorwindow
    - action: notify.all_mobile_apps
      metadata: {}
      data:
        message: Eine Tür oder ein Fenster ist länger als 15 Minuten geöffnet.
        title: Offene Tür/Fenster
        data:
          group: ha_doorwindow
          tag: ha_doorwindow
          actions:
          - action: URI
            icon: mdi:view-dashboard
            title: Übersicht öffnen
            uri: homeassistant://navigate/dashboard-raume/raeume
          push:
            sound:
              name: default
              critical: 1
              volume: 0.2
  mode: parallel
  max: 10
