# Loads default set of integrations. Do not remove.
default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Load cuomizations
homeassistant:
  packages: !include custom_packages/packages.yaml
  customize: !include_dir_merge_named custom_packages/customize/

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Load configurations
scene: !include custom_yaml/scenes.yaml
automation: !include custom_yaml/automations.yaml

logger:
  default: warn
#  logs:
#    homeassistant.components.rest_command: debug
