automation: !include_dir_merge_list automation/
input_boolean: !include_dir_merge_named input_boolean/
input_number: !include_dir_merge_named input_number/
template:
  - sensor: !include_dir_merge_list template_sensor/
timer: !include_dir_merge_named timer/
