# Automations
- alias: "Thermostate: Badezimmer OG Fenster geöffnet"
  id: eve_thermo_bath_first_floor_window_opened
  trigger:
    - platform: state
      entity_id: binary_sensor.fenster_badezimmer_og
      to: 'on'
  action:
    - service: climate.turn_off
      target:
        entity_id:
          - climate.heizung_badezimmer_og_fenster
          - climate.heizung_badezimmer_og_handtuchhalter