# Automations
- alias: "Thermostate: Badezeit Modus gestartet"
  id: eve_thermo_bath_time_mode_started
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.eve_thermo_badezimmer_bath_time_timer
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.eve_thermo_badezimmer_og_status