- alias: "Thermostate: Badezeit Modus gestoppt"
  id: eve_thermo_bath_time_mode_stopped
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.eve_thermo_badezimmer_bath_time_timer
    - platform: event
      event_type: timer.cancelled
      event_data:
        entity_id: timer.eve_thermo_badezimmer_bath_time_timer
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.eve_thermo_badezimmer_og_status