# Automations
- alias: "Thermostate: Badezimmer OG Fenster geschlossen"
  id: eve_thermo_bath_first_floor_window_closed
  trigger:
    - platform: state
      entity_id: binary_sensor.fenster_badezimmer_og
      to: 'off'
  action:
    - service: climate.turn_on
      target:
        entity_id:
          - climate.heizung_badezimmer_og_fenster
          - climate.heizung_badezimmer_og_handtuchhalter