# Automations
- alias: "Thermostate: Schlafzimmer Fenster geschlossen"
  id: eve_thermo_bedroom_window_closed
  trigger:
    - platform: state
      entity_id: binary_sensor.fenster_schlafzimmer
      to: 'off'
  condition: 
    - condition: state
      entity_id: binary_sensor.eve_thermostat_heating_enabled
      state: "on"
  action:
    - service: climate.turn_on
      target:
        entity_id:
          - climate.heizung_schlafzimmer_links
          - climate.heizung_schlafzimmer_rechts