# Automations
- alias: "Thermostate: Bibliothek Fenster geschlossen"
  id: eve_thermo_bibliothek_window_closed
  trigger:
    - platform: state
      entity_id: binary_sensor.fenster_bibliothek
      to: 'off'
  condition: 
    - condition: state
      entity_id: binary_sensor.eve_thermostat_heating_enabled
      state: "on"
  action:
    - service: climate.turn_on
      target:
        entity_id: climate.heizung_bibliotheke