# Automations
- alias: "Thermostate: Bibliothek Fenster geöffnet"
  id: eve_thermo_bibliothek_window_opened
  trigger:
    - platform: state
      entity_id: binary_sensor.fenster_bibliothek
      to: 'on'
  action:
    - service: climate.turn_off
      target:
        entity_id: climate.heizung_bibliotheke