# Automations
- alias: "Thermostate: Flur Tür geöffnet"
  id: eve_thermo_corridor_door_opened
  trigger:
    - platform: state
      entity_id: binary_sensor.tur_flur
      to: "on"
  action:
    - service: climate.turn_off
      target:
        entity_id: climate.heizung_flur
