# Automations
- alias: "Thermostate: Flur Tür geschlossen"
  id: eve_thermo_corridor_door_closed
  trigger:
    - platform: state
      entity_id: binary_sensor.tur_flur
      to: "off"
  action:
    - service: climate.turn_on
      target:
        entity_id: climate.heizung_flur
