# Automations
- alias: "Thermostate: Esszimmer Steckdose deaktiviert"
  id: eve_thermo_dining_room_energy_deactivated
  trigger:
    - platform: state
      entity_id: switch.steckdose_esszimmer
      to: "off"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.eve_thermo_esszimmer_status
