# Automations
- alias: "Thermostate: Esszimmer Tür geschlossen"
  id: eve_thermo_dining_room_door_closed
  trigger:
    - platform: state
      entity_id: binary_sensor.tur_esszimmer_tur
      to: "off"
  condition: 
    - condition: state
      entity_id: binary_sensor.eve_thermostat_heating_enabled
      state: "on"
  action:
    - service: climate.turn_on
      target:
        entity_id:
          - climate.heizung_esszimmer_links
          - climate.heizung_esszimmer_rechts
