# Automations
- alias: "Thermostate: Esszimmer Steckdose aktiviert"
  id: eve_thermo_dining_room_energy_activated
  trigger:
    - platform: state
      entity_id: switch.steckdose_esszimmer
      to: "on"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.eve_thermo_esszimmer_status
