- alias: "Thermostate: Gute Nacht Modus gestoppt"
  id: eve_thermo_good_night_mode_stopped
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.eve_thermo_schlafzimmer_good_night_timer
    - platform: event
      event_type: timer.cancelled
      event_data:
        entity_id: timer.eve_thermo_schlafzimmer_good_night_timer
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.eve_thermo_schlafzimmer_status