# Automations
- alias: "Thermostate: Gute Nacht Modus gestartet"
  id: eve_thermo_good_night_mode_started
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.eve_thermo_schlafzimmer_good_night_timer
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.eve_thermo_schlafzimmer_status
