# Automations
- alias: "Thermostate: Wohnzimmer Fenster geöffnet"
  id: eve_thermo_living_room_window_opened
  trigger:
    - platform: state
      entity_id: binary_sensor.fenster_wohnzimmer
      to: 'on'
  action:
    - service: climate.turn_off
      target:
        entity_id:
          - climate.heizung_wohnzimmer_links
          - climate.heizung_wohnzimmer_rechts