# Automations
- alias: "Thermostate: Wohnzimmer Steckdose aktiviert"
  id: eve_thermo_living_room_energy_activated
  trigger:
    - platform: state
      entity_id: switch.steckdose_wohnzimmer
      to: 'on'
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.eve_thermo_wohnzimmer_status