# Automations
- alias: "Thermostate: Wohnzimmer Fenster geschlossen"
  id: eve_thermo_living_room_window_closed
  trigger:
    - platform: state
      entity_id: binary_sensor.fenster_wohnzimmer
      to: 'off'
  action:
    - service: climate.turn_on
      target:
        entity_id:
          - climate.heizung_wohnzimmer_links
          - climate.heizung_wohnzimmer_rechts