# Automations
- alias: "Thermostate: Nähzimmer Steckdose aktiviert"
  id: eve_thermo_sewing_room_energy_activated
  trigger:
    - platform: state
      entity_id: switch.steckdose_naehzimmer
      to: "on"
  action:
    - service: switch.turn_on
      target: 
        entity_id: switch.eve_thermo_naehzimmer_status
