- alias: "Thermostate: Badezeit Modus gestoppt"
  id: eve_thermo_bath_time_mode_stopped
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.eve_thermo_badezimmer_bath_time_timer
    - platform: event
      event_type: timer.cancelled
      event_data:
        entity_id: timer.eve_thermo_badezimmer_bath_time_timer
  action:
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heizung_badezimmer_og_fenster
          - climate.heizung_badezimmer_og_handtuchhalter
      data:
        temperature: "{{- states('input_number.eve_thermo_badezimmer_og_min') -}}"