# Automations
- alias: "Thermostate: Alle Thermostate abschalten"
  id: eve_thermo_heating_disabled
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.eve_thermostat_heating_enabled
      to: "off"
  condition:
    condition: state
    entity_id: automation.thermostate_alle_thermostate_einschalten
    attribute: current
    state: 0
  action:
    - service: climate.turn_off
      target:
        entity_id:
          - climate.heizung_badezimmer_eg
          - climate.heizung_badezimmer_og_fenster
          - climate.heizung_badezimmer_og_handtuchhalter
          - climate.heizung_bibliotheke
          - climate.heizung_esszimmer_links
          - climate.heizung_esszimmer_rechts
          - climate.heizung_flur
          - climate.heizung_kinderzimmer
          - climate.heizung_kueche
          - climate.heizung_naehzimmer
          - climate.heizung_schlafzimmer_links
          - climate.heizung_schlafzimmer_rechts
          - climate.heizung_wohnzimmer_links
          - climate.heizung_wohnzimmer_rechts
