# Automations
- alias: "Thermostate: Schlafzimmer aktivieren"
  id: eve_thermo_turn_on_bedroom
  trigger:
    - platform: state
      entity_id: binary_sensor.fenster_schlafzimmer
      to: 'off'
  action:
    - service: climate.turn_on
      target:
        entity_id:
          - climate.heizung_schlafzimmer_links
          - climate.heizung_schlafzimmer_rechts