# Automations
- alias: "Thermostate: Bibliothek aktivieren"
  id: eve_thermo_turn_on_bibliothek
  trigger:
    - platform: state
      entity_id: binary_sensor.fenster_bibliothek
      to: 'off'
  action:
    - service: climate.turn_on
      target:
        entity_id: climate.heizung_bibliotheke