# Automations
- alias: "Thermostate: Flur deaktivieren"
  id: eve_thermo_turn_off_corridor
  trigger:
    - platform: state
      entity_id: binary_sensor.tur_flur
      to: "on"
  action:
    - service: climate.turn_off
      target:
        entity_id: climate.heizung_flur
