# Automations
- alias: "Thermostate: Flur aktivieren"
  id: eve_thermo_turn_on_corridor
  trigger:
    - platform: state
      entity_id: binary_sensor.tur_flur
      to: "off"
  action:
    - service: climate.turn_on
      target:
        entity_id: climate.heizung_flur
