# Automations
- alias: "Thermostate: Schlafzimmer deaktivieren"
  id: eve_thermo_turn_off_bedroom
  trigger:
    - platform: state
      entity_id: binary_sensor.fenster_schlafzimmer
      to: 'on'
  action:
    - service: climate.turn_off
      target:
        entity_id:
          - climate.heizung_schlafzimmer_links
          - climate.heizung_schlafzimmer_rechts