# Automations
- alias: "Thermostate: Schlafzimmer deaktivieren"
  id: eve_thermo_turn_off_dining_room
  trigger:
    - platform: state
      entity_id: binary_sensor.tur_esszimmer_tur
      to: "on"
  action:
    - service: climate.turn_off
      target:
        entity_id:
          - climate.heizung_esszimmer_links
          - climate.heizung_esszimmer_rechts
