- platform: template
  name: ev6_charge_port
  availability_template: "{{- is_state('sensor.ev6_data', 'on') -}}"
  value_template: "{{- is_state('binary_sensor.ev6_ev_charge_port', 'off') -}}"
  lock:
    - service: kia_uvo.close_charge_port
      data:
        device_id: 6ac735d8cb8f48b7ef4b35fc85f0b2f2
  unlock:
    - service: kia_uvo.open_charge_port
      data:
        device_id: 6ac735d8cb8f48b7ef4b35fc85f0b2f2