# Frontend input text controls:
external_access_dnydns_base_url:
  name: external_access_dnydns_base_url
  icon: mdi:web
  pattern: '(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9\-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9\-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})'
external_access_dnydns_username:
  name: external_access_dnydns_username
  icon: mdi:account
  pattern: '[^\s]+'
  mode: password
external_access_dnydns_password:
  name: external_access_dnydns_password
  icon: mdi:lock
  pattern: '[^\s]+'
  mode: password
