# Automations
- alias: "Update Sensor: nina_xrepository_ars"
  id: update_nina_xrepository_ars
  trigger:
    platform: time_pattern
    seconds: "/10"
  condition:
    condition: and
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.nina_xrepository_ars
            state: "OK"
      - condition: state
        entity_id: binary_sensor.nina_xrepository_ars_ready
        state: "on"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.nina_xrepository_ars
- alias: "Update Sensor: nina_warning"
  id: update_nina_warning
  trigger:
    platform: time_pattern
    seconds: "/10"
  condition:
    condition: and
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.nina_warning
            state: "OK"
      - condition: state
        entity_id: binary_sensor.nina_warning_ready
        state: "on"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.nina_warning
