# Automations
- alias: "Update Sensors: addon_running_states"
  id: update_addon_running_states
  mode: single
  max_exceeded: silent
  trigger:
    platform: time_pattern
    seconds: "/10"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: binary_sensor.sqlite_web_lauft
    - service: homeassistant.update_entity
      target:
        entity_id: binary_sensor.advanced_ssh_web_terminal_lauft
    - service: homeassistant.update_entity
      target:
        entity_id: binary_sensor.studio_code_server_lauft
