# <summary>
# This YAML configuration contains template input number controls
# for the frontend to set the EZ1 maximum energy.
# </summary>
# <remarks>
# =========================================================================
# Date         Author        Comment
# 2024-03-11   FZE           Initial release
# =========================================================================
# </remarks>

# <summary>
# This YAML configuration contains template input switch controls
# for the frontend to set the EZ1 On/Off state.
# </summary>
# <remarks>
# =========================================================================
# Date         Author        Comment
# 2024-03-11   FZE           Initial release
# =========================================================================
# </remarks>

# <summary>
# The currently set maximal power of the device.
# </summary>
- unique_id: apsystems_ez1_max_power
  name: apsystems_ez1_max_power
  icon: mdi:lightning-bolt-circle
  availability: |-
    {{-
      is_state('sensor.apsystems_ez1_state', 'OK')
      and is_number(state_attr('sensor.apsystems_ez1_state', 'currentMaxPower'))
      and is_number(state_attr('sensor.apsystems_ez1_state', 'minPower'))
      and is_number(state_attr('sensor.apsystems_ez1_state', 'maxPower'))
    -}}
  state: "{{- state_attr('sensor.apsystems_ez1_state', 'currentMaxPower') | int -}}"
  set_value:
    - service: rest_command.apsystems_setmaxpower
      data:
        power: "{{- this.state -}}"
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.apsystems_getMaxPower
  step: 1
  min: "{{- state_attr('sensor.apsystems_ez1_state', 'minPower') | int -}}"
  max: "{{- state_attr('sensor.apsystems_ez1_state', 'maxPower') | int -}}"
