# Automations
- alias: "Keller-Pumpe: Abschalt Countdown starten"
  id: pump_control_cancel_stop_timer
  trigger:
    - platform: state
      entity_id: sensor.pump_control_status
      to: "on"
  action:
    - service: timer.cancel
      target:
        entity_id: timer.pump_control_stop_timer
    - service: timer.cancel
      target:
        entity_id: timer.pump_control_start_timer
