# Automations
- alias: "Keller-Pumpe: Einschalt Countdown abbrechen"
  id: pump_control_cancel_start_timer
  trigger:
    - platform: state
      entity_id: sensor.pump_control_status
      from: "off"
    - platform: state
      entity_id: input_boolean.pump_control_use_auto_start
      to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.pump_control_enabled
      state: "on"
  action:
    - service: timer.cancel
      target:
        entity_id: timer.pump_control_start_timer

- alias: "Keller-Pumpe: Abschalt Countdown abbrechen"
  id: pump_control_cancel_stop_timer
  trigger:
    - platform: state
      entity_id: sensor.pump_control_status
      to: "off"
    - platform: state
      entity_id: sensor.pump_control_status
      to: "on"
  action:
    - service: timer.cancel
      target:
        entity_id: timer.pump_control_stop_timer
