# Automations
- alias: "Garten-Pumpe: Steuern"
  id: pump_control_start_garden_pump
  trigger:
    - platform: time
      at: "07:20:00"
    - platform: time
      at: "19:20:00"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.steckdose_gartenpumpe
    - delay:
        minutes: 30
    - service: switch.turn_off
      target:
        entity_id: switch.steckdose_gartenpumpe
