# Automations
- alias: "Keller-Pumpe: Stärung behoben"
  id: pump_control_notify_pump_jam_resolved
  trigger:
    - platform: state
      entity_id: input_boolean.pump_control_jammed
      to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.pump_control_enabled
      state: "on"
  action:
    - service: notify.all_mobile_apps
      data:
        message: "clear_notification"
        data:
          tag: "ha_pump_control_jammed"
    - service: switch.turn_on
      target:
        entity_id: switch.steckdose_keller
