# Automations
- alias: "Keller-Pumpe: Störungs-Abschaltung"
  id: pump_control_notify_pump_jammed
  trigger:
    - platform: state
      entity_id: sensor.pump_control_status
      to: "jammed"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.steckdose_keller
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.pump_control_jammed
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.pump_control_water_alert_send
    - service: notify.all_mobile_apps
      data:
        message: "clear_notification"
        data:
          tag: "ha_pump_started"
    - service: notify.all_mobile_apps
      data:
        message: "clear_notification"
        data:
          tag: "ha_pump_stopped"
    - service: notify.all_mobile_apps
      data:
        message: "clear_notification"
        data:
          tag: "ha_pump_unknown"
    - service: notify.all_mobile_apps
      data:
        title: "Störung der Keller Pumpe"
        message: "Halte die Benachrichtung gedrückt für weitere Optionen."
        data:
          group: "ha_pump_control"
          subtitle: "Die Pumpe im Keller ist gestört und wurde abgschaltet!"
          tag: "ha_pump_control_jammed"
          actions:
            - action: "URI"
              icon: mdi:home-floor-b
              title: "Keller ansehen"
              uri: "/dashboard-raume/keller"
          push:
            sound:
              name: "default"
              critical: 1
              volume: 0.2

