# Automations
- alias: "Keller-Pumpe: Einschalt Countdown starten"
  id: pump_control_start_start_timer
  trigger:
    - platform: state
      entity_id: sensor.pump_control_status
      to: "off"
    - platform: homeassistant
      event: "start"
  condition:
    - condition: state
      entity_id: input_boolean.pump_control_use_auto_start
      state: "on"
  action:
    - service: timer.start
      target:
        entity_id: timer.pump_control_start_timer
      data:
        duration: |-
          {{-
            "%0.2d"| format(states("input_number.pump_control_auto_start_interval") | int)
            + ":00:00"
          -}}
