# Automations
- alias: "Keller-Pumpe: Starten"
  id: pump_control_start_pump
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.pump_control_start_timer
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.pump_control_enabled
        state: "on"
      - condition: state
        entity_id: input_boolean.pump_control_jammed
        state: "off"
      - condition: state
        entity_id: switch.steckdose_keller
        state: "off"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.steckdose_keller
