# Automations
- alias: "Update Sensor: pump_control_start_timer_remaining_time"
  id: update_pump_control_start_timer_remaining_time
  trigger:
    platform: time_pattern
    seconds: "/1"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.pump_control_enabled
        state: "on"
      - condition: state
        entity_id: timer.pump_control_start_timer
        state: "active"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.pump_control_start_timer_remaining_time

- alias: "Update Sensor: pump_control_stop_timer_remaining_time"
  id: update_pump_control_stop_timer_remaining_time
  trigger:
    platform: time_pattern
    seconds: "/1"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.pump_control_enabled
        state: "on"
      - condition: state
        entity_id: timer.pump_control_stop_timer
        state: "active"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.pump_control_stop_timer_remaining_time