# Group sensors
- platform: group
  unique_id: eve_thermostat_mean_livingroom
  name: eve_thermostat_mean_livingroom
  type: mean
  unit_of_measurement: "°C"
  ignore_non_numeric: true
  device_class: temperature
  state_class: measurement
  entities:
    - sensor.eve_thermostat_livingroom_left_temperature
    - sensor.eve_thermostat_livingroom_right_temperature
- platform: group
  unique_id: eve_thermostat_mean_diningroom
  name: eve_thermostat_mean_diningroom
  type: mean
  unit_of_measurement: "°C"
  ignore_non_numeric: true
  device_class: temperature
  state_class: measurement
  entities:
    - sensor.eve_thermostat_diningroom_left_temperature
    - sensor.eve_thermostat_diningroom_right_temperature
- platform: group
  unique_id: eve_thermostat_mean_bedroom
  name: eve_thermostat_mean_bedroom
  type: mean
  unit_of_measurement: "°C"
  ignore_non_numeric: true
  device_class: temperature
  state_class: measurement
  entities:
    - sensor.eve_thermostat_bedroom_left_temperature
    - sensor.eve_thermostat_bedroom_right_temperature
- platform: group
  unique_id: eve_thermostat_mean_bath_first_floor
  name: eve_thermostat_mean_bath_first_floor
  type: mean
  unit_of_measurement: "°C"
  ignore_non_numeric: true
  device_class: temperature
  state_class: measurement
  entities:
    - sensor.eve_thermostat_bath_first_floor_window_temperature
    - sensor.eve_thermostat_bath_first_floor_towel_rail_temperature
- platform: group
  unique_id: eve_thermostat_mean_ground_floor
  name: eve_thermostat_mean_ground_floor
  type: mean
  unit_of_measurement: "°C"
  ignore_non_numeric: true
  device_class: temperature
  state_class: measurement
  entities:
    - sensor.eve_thermostat_corridor_temperature
    - sensor.eve_thermostat_kitchen_temperature
    - sensor.eve_thermostat_bath_ground_floor_temperature
    - sensor.eve_thermostat_mean_livingroom
    - sensor.eve_thermostat_mean_diningroom
- platform: group
  unique_id: eve_thermostat_mean_first_floor
  name: eve_thermostat_mean_first_floor
  type: mean
  unit_of_measurement: "°C"
  ignore_non_numeric: true
  device_class: temperature
  state_class: measurement
  entities:
    - sensor.eve_thermostat_library_temperature
    - sensor.eve_thermostat_sewingroom_temperature
    - sensor.eve_thermostat_childrens_room_temperature
    - sensor.eve_thermostat_mean_bath_first_floor
    - sensor.eve_thermostat_mean_bedroom
- platform: group
  unique_id: eve_thermostat_mean_house
  name: eve_thermostat_mean_house
  type: mean
  unit_of_measurement: "°C"
  ignore_non_numeric: true
  device_class: temperature
  state_class: measurement
  entities:
    - sensor.eve_thermostat_mean_ground_floor
    - sensor.eve_thermostat_mean_first_floor
- platform: group
  unique_id: eve_thermostat_min_house
  name: eve_thermostat_min_house
  type: min
  unit_of_measurement: "°C"
  ignore_non_numeric: true
  device_class: temperature
  state_class: measurement
  entities:
    - sensor.eve_thermostat_corridor_temperature
    - sensor.eve_thermostat_bath_ground_floor_temperature
    - sensor.eve_thermostat_kitchen_temperature
    - sensor.eve_thermostat_library_temperature
    - sensor.eve_thermostat_sewingroom_temperature
    - sensor.eve_thermostat_childrens_room_temperature
    - sensor.eve_thermostat_bath_first_floor_window_temperature
    - sensor.eve_thermostat_bath_first_floor_towel_rail_temperature
    - sensor.eve_thermostat_livingroom_right_temperature
    - sensor.eve_thermostat_livingroom_left_temperature
    - sensor.eve_thermostat_diningroom_right_temperature
    - sensor.eve_thermostat_diningroom_left_temperature
    - sensor.eve_thermostat_bedroom_left_temperature
    - sensor.eve_thermostat_bedroom_right_temperature
- platform: group
  unique_id: eve_thermostat_max_house
  name: eve_thermostat_max_house
  type: max
  unit_of_measurement: "°C"
  ignore_non_numeric: true
  device_class: temperature
  state_class: measurement
  entities:
    - sensor.eve_thermostat_corridor_temperature
    - sensor.eve_thermostat_bath_ground_floor_temperature
    - sensor.eve_thermostat_kitchen_temperature
    - sensor.eve_thermostat_library_temperature
    - sensor.eve_thermostat_sewingroom_temperature
    - sensor.eve_thermostat_childrens_room_temperature
    - sensor.eve_thermostat_bath_first_floor_window_temperature
    - sensor.eve_thermostat_bath_first_floor_towel_rail_temperature
    - sensor.eve_thermostat_livingroom_right_temperature
    - sensor.eve_thermostat_livingroom_left_temperature
    - sensor.eve_thermostat_diningroom_right_temperature
    - sensor.eve_thermostat_diningroom_left_temperature
    - sensor.eve_thermostat_bedroom_left_temperature
    - sensor.eve_thermostat_bedroom_right_temperature
- platform: group
  unique_id: eve_thermostat_range_house
  name: eve_thermostat_range_house
  type: range
  unit_of_measurement: "°C"
  ignore_non_numeric: true
  device_class: temperature
  state_class: measurement
  entities:
    - sensor.eve_thermostat_corridor_temperature
    - sensor.eve_thermostat_kitchen_temperature
    - sensor.eve_thermostat_library_temperature
    - sensor.eve_thermostat_sewingroom_temperature
    - sensor.eve_thermostat_childrens_room_temperature
    - sensor.eve_thermostat_bath_first_floor_window_temperature
    - sensor.eve_thermostat_bath_first_floor_towel_rail_temperature
    - sensor.eve_thermostat_livingroom_right_temperature
    - sensor.eve_thermostat_livingroom_left_temperature
    - sensor.eve_thermostat_diningroom_right_temperature
    - sensor.eve_thermostat_diningroom_left_temperature
    - sensor.eve_thermostat_bedroom_left_temperature
    - sensor.eve_thermostat_bedroom_right_temperature
