# <summary>
# This YAML configuration contains
# the configuration of the garden pump custom package.
# </summary>
# <remarks>
# =========================================================================
# Date         Author        Comment
# 2024-08-12   FZE           Initial release
# =========================================================================
# </remarks>

automation: !include_dir_merge_list automation/
input_boolean: !include_dir_merge_named input_boolean/
input_datetime: !include_dir_merge_named input_datetime/
input_number: !include_dir_merge_named input_number/
template:
  - sensor: !include_dir_merge_list template_sensor/
timer: !include_dir_merge_named timer/
