# Automations
- alias: "Degu-Licht: stoppen"
  id: degu_light_stop_degu_light_timer
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.degu_light_stop_timer
    - platform: event
      event_type: timer.cancelled
      event_data:
        entity_id: timer.degu_light_stop_timer
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.steckdose_degu_licht
