# Group sensors
- platform: group
  unique_id: all_mobile_apps
  name: all_mobile_apps
  services:
    - service: mobile_app_ipad_von_florian
    - service: mobile_app_ipad_von_manuela
    - service: mobile_app_iphone_von_florian
    - service: mobile_app_iphone_von_manuela
