# Automations
- alias: "Update Sensor: home_address"
  id: update_home_address
  mode: single
  max_exceeded: silent
  trigger:
    platform: time_pattern
    seconds: "/10"
  condition:
    condition: and
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.home_address_data
            state: "OK"
      - condition: state
        entity_id: binary_sensor.home_address_ready
        state: "on"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.home_address_data
