# Integration sensors
- platform: integration
  unique_id: evcc_average_grid_reference_power
  name: evcc_average_grid_reference_power
  source: sensor.evcc_grid_reference_power
  method: left
  unit_prefix: k
  round: 2
- platform: integration
  unique_id: evcc_average_grid_delivery_power
  name: evcc_average_grid_delivery_power
  source: sensor.evcc_grid_delivery_power
  method: left
  unit_prefix: k
  round: 2
- platform: integration
  unique_id: evcc_average_pv_delivery_power
  name: evcc_average_pv_delivery_power
  source: sensor.evcc_pv_delivery_power
  method: left
  unit_prefix: k
  round: 2
- platform: integration
  unique_id: evcc_average_battery_charging_power
  name: evcc_average_battery_charging_power
  source: sensor.evcc_battery_charging_power
  method: left
  unit_prefix: k
  round: 2
- platform: integration
  unique_id: evcc_average_battery_discharging_power
  name: evcc_average_battery_discharging_power
  source: sensor.evcc_battery_discharging_power
  method: left
  unit_prefix: k
  round: 2
- platform: integration
  unique_id: evcc_average_home_consumption_power
  name: evcc_average_home_consumption_power
  source: sensor.evcc_home_consumption_power
  method: left
  unit_prefix: k
  round: 2
- platform: integration
  unique_id: evcc_average_home_consumption_without_devices_power
  name: evcc_average_home_consumption_without_devices_power
  source: sensor.evcc_home_consumption_power
  method: left
  unit_prefix: k
  round: 2
- platform: integration
  unique_id: evcc_average_wallbox_charging_power
  name: evcc_average_wallbox_charging_power
  source: sensor.evcc_wallbox_charging_power
  method: left
  unit_prefix: k
  round: 2
- platform: integration
  unique_id: evcc_average_green_power
  name: evcc_average_green_power
  source: sensor.evcc_green_power
  method: left
  unit_prefix: k
  round: 2
