# Integration sensors
- platform: integration
  unique_id: evcc_gridpower_receiving_total
  name: evcc_gridpower_receiving_total
  source: sensor.evcc_gridpower_receiving
  method: left
  unit_prefix: k
  round: 2
- platform: integration
  unique_id: evcc_gridpower_distributing_total
  name: evcc_gridpower_distributing_total
  source: sensor.evcc_gridpower_distributing
  method: left
  unit_prefix: k
  round: 2
- platform: integration
  unique_id: evcc_batterypower_charging_total
  name: evcc_batterypower_charging_total
  source: sensor.evcc_batterypower_charging
  method: left
  unit_prefix: k
  round: 2
- platform: integration
  unique_id: evcc_batterypower_discharging_total
  name: evcc_batterypower_discharging_total
  source: sensor.evcc_batterypower_discharging
  method: left
  unit_prefix: k
  round: 2