# <summary>
# This YAML configuration contains
# the automation to notify users of a basement pump emergency stop.
# </summary>
# <remarks>
# =========================================================================
# Date         Author        Comment
# 2024-08-12   FZE           Initial release
# =========================================================================
# </remarks>

- alias: "Keller-Pumpe: Benachrichtigung über Notfall-Abschaltung"
  id: basement_pump_notify_emergency_stop
  trigger:
    platform: state
    entity_id: input_boolean.basement_pump_jammed
    to: "on"
  action:
    - action: input_boolean.turn_off
      target:
        entity_id: input_boolean.basement_pump_mute_notification
    - action: notify.all_mobile_apps
      data:
        message: "clear_notification"
        data:
          tag: "ha_basement_pump"
    - action: notify.all_mobile_apps
      data:
        title: "Störung der Keller Pumpe"
        message: "Halte die Benachrichtung gedrückt für weitere Optionen."
        data:
          group: "ha_basement_pump"
          subtitle: "Die Pumpe im Keller ist gestört und wurde abgschaltet!"
          tag: "ha_basement_pump"
          actions:
            - action: "URI"
              icon: mdi:home-floor-b
              title: "Keller ansehen"
              uri: "homeassistant://navigate/dashboard-raume/keller"
          push:
            sound:
              name: "default"
              critical: 1
              volume: 0.2
