# <summary>
# This YAML configuration contains
# the automation to start the basement pump.
# </summary>
# <remarks>
# =========================================================================
# Date         Author        Comment
# 2024-08-12   FZE           Initial release
# =========================================================================
# </remarks>

- alias: 'Keller-Pumpe: Starten'
  id: basement_pump_start
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.basement_pump_start_timer
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.steckdose_keller
        state: 'off'
      - condition: state
        entity_id: input_boolean.basement_pump_jammed
        state: 'off'
  action:
    action: switch.turn_on
    target:
      entity_id: switch.steckdose_keller
