# <summary>
# This YAML configuration contains
# the automation to cancel the garden pump preasure timer.
# </summary>
# <remarks>
# =========================================================================
# Date         Author        Comment
# 2024-08-12   FZE           Initial release
# =========================================================================
# </remarks>

- alias: "Garten-Pumpe: Countdown für den Druckerhalt abbrechen"
  id: basement_pump_cancel_preasure_timer
  trigger:
    - platform: state
      entity_id: input_boolean.garden_pump_enabled
      to: "off"
    - platform: state
      entity_id: input_boolean.garden_pump_autostart_preasure
      to: "off"
  action:
    action: timer.cancel
    target:
      entity_id: timer.garden_pump_next_preasure_timer