# <summary>
# This YAML configuration contains
# the automation to start pouring with the garden pump.
# </summary>
# <remarks>
# =========================================================================
# Date         Author        Comment
# 2024-08-12   FZE           Initial release
# 2024-08-13   FZE           Added buffer for time differences
# =========================================================================
# </remarks>

- alias: "Garten-Pumpe: Start des Gießvorgangs"
  id: garden_pump_start_pouring
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.garden_pump_next_pouring_timer
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.garden_pump_enabled
        state: "on"
      - condition: state
        entity_id: switch.steckdose_gartenpumpe
        state: "off"
      - condition: state
        entity_id: input_boolean.garden_pump_autostart_pouring
        state: "on"
  action:
    - action: switch.turn_on
      target:
        entity_id: switch.steckdose_gartenpumpe
    - event: garden_pump_pouring_started
    - delay:
        minutes: "{{- states('input_number.garden_pump_duration_pouring') | int + (2 * states('input_number.garden_pump_buffer_pouring') | int) -}}"
    - action: switch.turn_off
      target:
        entity_id: switch.steckdose_gartenpumpe
