# <summary>
# This YAML configuration contains
# the automation to update the remaining time
# of the start preasure garden pump sensors in the frontend.
# </summary>
# <remarks>
# =========================================================================
# Date         Author        Comment
# 2024-08-12   FZE           Initial release
# =========================================================================
# </remarks>

- alias: 'Update Sensor: garden_pump_remaining_time_start_preasure'
  id: update_sensor_garden_pump_remaining_time_start_preasure
  trigger:
    platform: time_pattern
    seconds: '/1'
  condition:
    condition: state
    entity_id: timer.garden_pump_next_preasure_timer
    state: 'active'
  action:
    action: homeassistant.update_entity
    target:
      entity_id: sensor.garden_pump_remaining_time_start_preasure
