automation: !include_dir_merge_list automation/
input_number: !include_dir_merge_named input_number/
sensor: !include_dir_merge_list sensor/
switch:
  - platform: template
    switches: !include_dir_merge_named switch/
template:
  - binary_sensor: !include_dir_merge_list template_binary_sensor/
  - sensor: !include_dir_merge_list template_sensor/
timer: !include_dir_merge_named timer/
