# Automations
- alias: "Update Sensor: river_level_current_measurement"
  id: update_river_level_current_measurement
  trigger:
    platform: time_pattern
    seconds: "/10"
  condition:
    condition: and
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.river_level_current_measurement
            state: "OK"
      - condition: state
        entity_id: binary_sensor.river_measurements_ready
        state: "on"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.river_level_current_measurement
- alias: "Update Sensor: river_level_next_station"
  id: update_river_level_next_station
  trigger:
    platform: time_pattern
    seconds: "/10"
  condition:
    condition: and
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.river_level_next_station
            state: "OK"
      - condition: state
        entity_id: binary_sensor.river_station_ready
        state: "on"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.river_level_next_station
