# Automations
- alias: "Tür & Fenster Alarm: Countdown zum reaktivieren abbrechen"
  id: eve_door_window_cancel_reset_alarm_countdown
  trigger:
    - platform: state
      entity_id: input_boolean.eve_door_window_alarm_disabled
      to: "off"
    - platform: state
      entity_id:
        - zone.home
      to: "0"
  action:
    - service: timer.cancel
      target:
        entity_id: timer.eve_door_window_reset_alarm
    - service: homeassistant.update_entity
      target:
        entity_id:
          - binary_sensor.tur_flur
          - binary_sensor.tur_esszimmer_tur
          - binary_sensor.fenster_badezimmer_og
          - binary_sensor.fenster_bibliothek
          - binary_sensor.fenster_wohnzimmer
          - binary_sensor.fenster_schlafzimmer
