# Automations
- alias: "Tür & Fenster Alarm: Reaktivieren"
  id: eve_door_window_reset_alarm
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.eve_door_window_reset_alarm
    - platform: event
      event_type: timer.cancelled
      event_data:
        entity_id: timer.eve_door_window_reset_alarm
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.eve_door_window_alarm_disabled
