# Automations
- alias: "Update Sensor: eve_door_window_remaining_time"
  id: update_eve_door_window_remaining_time
  mode: single
  max_exceeded: silent
  trigger:
    platform: time_pattern
    seconds: "/1"
  condition:
    condition: state
    entity_id: timer.eve_door_window_reset_alarm
    state: "active"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.eve_door_window_remaining_time
