# Group switches
- platform: group
  unique_id: all_energy_plugs
  name: all_energy_plugs
  entities:
    - switch.heizung_sauna
    - switch.steckdose_bibliothek
    - switch.steckdose_degu_licht
    - switch.steckdose_esszimmer
    - switch.steckdose_gartenpumpe
    - switch.steckdose_keller
    - switch.steckdose_naehzimmer
    - switch.steckdose_sauna
    - switch.steckdose_wohnzimmer
- platform: group
  unique_id: all_hotspots
  name: all_hotspots
  entities:
    - switch.fritz_box_7590_wi_fi_fritz_hotspot