# Automations
- alias: "Refresh Let's Encrypt Certificate"
  id: externakl_access_update_cert
  mode: single
  trigger:
    - platform: time
      at: "05:30:00"
  condition:
    - condition: time
      before: "05:00:00"
      after: "06:00:00"
      weekday:
        - sun
  action:
    - service: hassio.addon_restart
      data:
        addon: core_letsencrypt
    - delay:
        minutes: 5
    - service: homeassistant.restart
      data: {}
